version: '2'
services:
  rawhide:
    image: "fedora:rawhide"
    command: /root/shared/rawhide.sh 
    volumes:
      - /root/shared/:/root/shared/
  latest:
    image: "fedora:latest"
    command: /root/shared/latest.sh 
    volumes_from:
      - rawhide
